#!/usr/bin/env python
import argparse
from datetime import datetime, timezone
from io import StringIO
import os
import subprocess
from subprocess import PIPE, Popen

import skyway
from skyway.cloud.aws import *
from skyway.cloud.gcp import *
from skyway.cloud.azure import *
from skyway.cloud.slurm import *
from skyway.cloud.oci import *

import colorama
from colorama import Fore

# export SKYWAYROOT=/project/rcc/trung/skyway-github
#./skyway_list --account=rcc-aws

class InstanceDescriptor:
    def __init__(self, jobname: str, account_name: str, node_type: str, walltime: str, vendor_name: str):
        self.jobname = jobname
        self.account_name = account_name
        self.node_type = node_type
        self.walltime = walltime
        self.vendor_name = vendor_name

        self.account = None
        if 'aws' in vendor_name:
            self.account = AWS(account_name)
        elif 'gcp' in vendor_name:
            self.account = GCP(account_name)
        elif 'azure' in vendor_name:
            self.account = AZURE(account_name)
        elif 'oci' in vendor_name:
            self.account = OCI(account_name)
        elif 'midway3' in vendor_name:
            self.account = SLURMCluster(account_name)

        self.user = os.environ['USER']

    def getBalance(self):
        # retrieve from database for the given account
        accumulating_cost, remaining_balance = self.account.get_cost_and_usage_from_db(user_name=self.user)
        return remaining_balance

    def getEstimateCost(self):
        pt = datetime.strptime(self.walltime, "%H:%M:%S")
        walltime_in_hours = int(pt.hour + pt.minute/60)
        if "midway3" in self.vendor_name:
            unit_price = 1.0 # float(self.account.get_unit_price(self.node_type))
        else:
            unit_price = float(self.account.get_unit_price(self.node_type))
        cost = walltime_in_hours * unit_price
        return cost
  
    def list_nodes(self):
        nodes, list_of_nodes = self.account.list_nodes(verbose=False) 
        return nodes

if __name__ == "__main__":

    colorama.init(autoreset=True)

    msg = "Skyway info"
    parser = argparse.ArgumentParser(description=msg)

    # get the env variable SKYWAYROOT
    skywayroot = os.environ['SKYWAYROOT']
    if skywayroot == "":
        raise Exception("SKYWAYROOT is not defined.")

    print(Fore.GREEN + f"Skyway v2.0")
    print(f"Copyright 2019-2024, Research Computing Center, University of Chicago")
    pwd = os.environ['PWD']
    cmd = f"cd {skywayroot}; git describe --always; cd {pwd}"
    p = subprocess.run(cmd, shell=True, text=True, capture_output=True)
    print(f"commit: {p.stdout}")


    print(f"List of useful commands:")
    headers=["Command", 'Description', 'Usage']
    
    data = []
    command = "skyway_nodetypes"
    description = "List all the VM types accessible by a cloud account"
    usage = "skyway_nodetypes -A rcc-aws"
    data.append([command, description, usage])

    command = "skyway_alloc"
    description = "Allocate/provision an instance"
    usage = "skyway_alloc -A rcc-aws -t 00:30:00 --constraint=t1"
    data.append([command, description, usage])

    command = "skyway_list"
    description = "List all the running instances under a cloud account "
    usage = "skyway_list -A rcc-aws"
    data.append([command, description, usage])

    command = "skyway_cancel"
    description = "Terminate a running instance under a cloud account "
    usage = "skyway_cancel -A rcc-aws -J your-run"
    data.append([command, description, usage])

    command = "skyway_transfer"
    description = "Tranfer data from/to a running instance under a cloud account "
    usage = "skyway_transfer -A rcc-aws -J your-run training.py input.data"
    data.append([command, description, usage])

    command = "skyway_connect"
    description = "Connect to a running instance under a cloud account "
    usage = "skyway_connect -A rcc-aws -J your-run"
    data.append([command, description, usage])
    
    command = "skyway_interactive"
    description = "Create an interactive session on an instance under a cloud account "
    usage = "skyway_interactive -A rcc-aws -t 00:30:00 --constraint=g5"
    data.append([command, description, usage])

    command = "skyway_batch"
    description = "Submit a job script under a cloud account "
    usage = "skyway_batch job_script.sh"
    data.append([command, description, usage])

    command = "skyway_advisor"
    description = "Find resources for a job script"
    usage = "skyway_advisor job_script.sh"
    data.append([command, description, usage])

    print(tabulate(data, headers=headers))
    print("")